apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # This should match the labels of your Deployment
  ports:
    - protocol: TCP
      port: 80              # Port exposed by the Service
      targetPort: 8080        # Port on the container that the Service will forward to
      nodePort: 30007       # NodePort for external access (optional)
  type: NodePort           # Change to LoadBalancer if needed
