apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
spec:
  selector:
    app: dep-web-color  # This should match the label of your Deployment
  ports:
    - protocol: TCP
      port: 80              # Port that the service will expose
      targetPort: 80        # Port on the container that the service will forward to
      nodePort: 30007       # Specify a node port (optional; if omitted, one will be assigned)
  type: NodePort           # Exposes the service on each Node's IP at a static port
