apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: gift-deployment
        image: tatapong/cicd-project-repo:jk  # Replace with your actual image name
        ports:
        - containerPort: 80  # Port your application listens on