apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: alpine  # Using a lightweight image for demonstration
      command: ["sh", "-c", "sleep 3600"]  # Keeps the container running for 1 hour
      volumeMounts:
        - name: my-storage
          mountPath: /mnt/data  # The path in the container where the PVC will be mounted
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc  # Reference to the PVC
